### ISSUE TITLE
My WIP quote list

### ISSUE THREAD

**Issue by GeorgeHahn** [MehdiK/software-quotes#4]
Any quotes here you don't want?
## Todo
- [x] Deduplicate
- [x] Verify authors
- [x] Convert to markdown
- [x] use the existing tags (e.g. Humor, Laws etc) or add new ones (e.g. Debugging). If you add a new tag please also find and update the existing quotes that could benefit from the new tag.
- [x] Make sure the url is not too long. Basically you shouldn't create a url that's longer than any of the existing ones. Also the shortened url should still be a correct sentence and carry the message properly. Checkout "a-complex-system-that-works-was-a-simple-system-that-worked" for an example.
## Quotes

```
If debugging is the process of removing software bugs, then programming must be the process of putting them in.
```

Edsger Dijkstra 

```
There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult.
```

C.A.R. Hoare

```
 Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.
```

Brian Kernighan 

```
When debugging, novices insert corrective code; experts remove defective code.
```

Richard Pattis

```
Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter.
```

Eric S. Raymond (American programmer, open source software advocate, author of     The Cathedral and the Bazaar)

```
Walking on water and developing software from a specification are easy if both are frozen.
```

Edward V Berard

```
You can have the project:
    Done On Time
    Done On Budget
    Done Properly
Pick two.
```

Unknown

```
Some people, when confronted with a problem, think "I know, I'll use regular expressions."
Now they have two problems.
```

Jamie Zawinski

```
In theory, there is no difference between theory and practice. But, in practice, there is.
```

Jan L. A. van de Snepscheut

```
A good programmer is someone who always looks both ways before crossing a one-way street.
```

Doug Linder

```
Deleted code is debugged code.
```

Jeff Sickel

```
First, solve the problem. Then, write the code.
```

John Johnson

```
Good code is its own best documentation. As you're about to add a comment, ask yourself, "How can I improve the code so that this comment isn't needed?" Improve the code and then document it to make it even clearer.
```

Steve McConnell

```
Without requirements or design, programming is the art of adding bugs to an empty text file.
```

Louis Srygley 
## Need Author

```
There is not now, nor has there ever been, nor will there ever be, any programming language in which it is the least bit difficult to write bad code.
```

Flon's Law

```
Any code of your own that you haven't looked at for six or more months might as well have been written by someone else.
```

Eagleson's law

**Comment by MehdiK** [comment]
Cool, thanks. Here is what I think we could add:

"If debugging is the process of removing software bugs, then programming must be the process of putting them in."

"When debugging, novices insert corrective code; experts remove defective code."

"Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter."

"Walking on water and developing software from a specification are easy if both are frozen."

"You can have the project:
    Done On Time
    Done On Budget
    Done Properly
Pick two."

"A good programmer is someone who always looks both ways before crossing a one-way street."

"Deleted code is debugged code."

"First, solve the problem. Then, write the code."

"Without requirements or design, programming is the art of adding bugs to an empty text file."

"Any code of your own that you haven't looked at for six or more months might as well have been written by someone else."

**Comment by MehdiK** [comment]
I also added two entries to your checklist.

**Comment by GeorgeHahn** [comment]
I used the "bugs" category rather than making a new "debugging" category - they feel similar enough that the decision between the two would be somewhat arbitrary.
